spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring-boot
  thymeleaf:
    reactive:
      max-chunk-size: 1024
      chunked-mode-view-names: list-chunked

config:
  uploads:
    path: /tmp/